#### Numpy (part-1)

In [1]:
import numpy as np

In [3]:
# convert list to array-

l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
arr= np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
# or we can also convert list to array using this function-

np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr1= np.array([[1,2,3],[4,5,6]])

In [13]:
# arr is 1 dimensional array and arr1 is 2 dimensional array, we can check using this-

arr.ndim

1

In [10]:
arr1.ndim

2

In [11]:
# convert list to matrix-

np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [15]:
mat= np.matrix(l)

In [12]:
# by default matrix has minimum dimension 2, so the list is turned into a matrix of 2 dimensions

In [16]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [17]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [18]:
#there's still no change, it is still matrix. This is because asanyarray function converts anything which is not an array
#into an array. As matrix is a 2-D array i.e. a subset of array, so asanyarray has no effect on matrix. 

In [19]:
# shallow copy-

arr

array([1, 2, 3, 4, 5])

In [20]:
a= arr  # shallow copy

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
arr[0]= 100

In [23]:
arr

array([100,   2,   3,   4,   5])

In [24]:
a

array([100,   2,   3,   4,   5])

In [25]:
# this is called shallow copy. Any changes in arr is reflected in a too. 
# This is because for the array created in the memory location, arr was pointing to that array.
# Now when a=arr, it simply means a is also pointing to that array.

In [26]:
# deep copy-

arr

array([100,   2,   3,   4,   5])

In [27]:
b= np.copy(arr)        # deep copy

In [28]:
b

array([100,   2,   3,   4,   5])

In [29]:
arr[0]= 300

In [30]:
arr

array([300,   2,   3,   4,   5])

In [31]:
b

array([100,   2,   3,   4,   5])

In [32]:
b[1]= 200

In [33]:
b

array([100, 200,   3,   4,   5])

In [34]:
arr

array([300,   2,   3,   4,   5])

In [ ]:
# this is called deep copy. Any changes in arr is not reflected in b and vice-versa. 
# This is because for the array created in memory location, arr was pointing to that array. 
# Now, when b= np.copy(arr), another memory location is created where that array is copied, 
# and b points to this new memory location now. 
# Therefore any changes in the array to which arr is pointing is not reflected in the array to which b is pointing.

In [35]:
# different ways to generate array or matrices-

np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
# (3,3) refers to shape i.e. 3x3, i refers to row indices and j refers to column indices

In [37]:
np.fromfunction( lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [39]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [40]:
iterable= [i*i for i in range(5)]

In [41]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [42]:
# so using fromiter() function and passing an iterable in it, we are able to generate array.

In [43]:
np.fromstring("23 45 56", sep= " ")

array([23., 45., 56.])

In [44]:
# so using fromstring() function which takes a string as argument, we are able to generate array.

In [45]:
np.fromstring("23,45,56", sep= ",")

array([23., 45., 56.])

In [46]:
# where ever there is comma in string, it separates the string and puts into array

In [47]:
arr

array([300,   2,   3,   4,   5])

In [48]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr.size

5

In [50]:
arr1.size

6

In [51]:
# size tells the no. of elements present in the array

In [52]:
arr.shape      

(5,)

In [53]:
arr1.shape

(2, 3)

In [54]:
# so arr1 array has 2 rows and 3 columns

In [55]:
arr.dtype

dtype('int64')

In [56]:
arr1.dtype

dtype('int64')

#### QUIZ

In [2]:
array= np.array([[1,2,3], [4,5,6]])

In [6]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
threshold= 3

In [8]:
for i in np.nditer(array):
    if i < threshold:
        i = 0

In [9]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
for i in range(np.shape(array)[0]):
    for j in range(np.shape(array)[1]):
        if array[i][j] < threshold:
            array[i][j] = 0

In [14]:
array

array([[0, 0, 3],
       [4, 5, 6]])

In [15]:
np.unique(array)

array([0, 3, 4, 5, 6])

In [17]:
array1= np.array([[1,3,5], [2,4,6]])

In [18]:
array1

array([[1, 3, 5],
       [2, 4, 6]])

In [24]:
np.concatenate((array, array1))

array([[0, 0, 3],
       [4, 5, 6],
       [1, 3, 5],
       [2, 4, 6]])

In [20]:
arr1= np.array([1,2,3])

In [21]:
arr2= np.array([4,5,6])

In [23]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [25]:
np.flip(arr1)

array([3, 2, 1])

In [28]:
np.argsort(np.array([3,2,7,1]))

array([3, 1, 0, 2])

#### Numpy (Part-2)

In [1]:
import numpy as np

##### Data generation i.e array generation 

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
# but if we give floating point numbers in range function, we will get error 
# because range() always takes an integer for the start point, end point and the step size

list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
# in numpy we have a function called arange() which takes floating point numbers as start, end and stepsize

np.arange(0.4,10.4,0.2)     # it will give an array with these data generated by arange() function

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [8]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [9]:
np.linspace(1,5,20)     # it will generate 20 points between 1 and 5 and each point is equally spaced

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
np.logspace(1,5,10)       # it will generate log of 10 data points between 1 and 5. By default log base is 10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [12]:
np.zeros(5)         # it will generate a 1-D array with 5 zeroes

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,4))         # it will generate 2-D array of shape (3,4) i.e 3 rows and 4 columns filled with 0s

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((3,4,2))   # it will generate 3-D array

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
# it generates 3 such (4,2) shape arrays. all the elements are 0s

In [17]:
np.zeros((3,4,2,3))     # it will generate a 4-D array

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [18]:
# 4 such (2,3) shape arrays will be generated and this entire structure is repeated 3 times thus giving a 4-D array.
# we can generate n dimensional array

In [19]:
np.ones(5)       # 1-D array with 5 ones is generated

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((2,3))          # 2-D array of shape (2,3) i.e 2 rows and 3 columns filled with 1s is generated

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
arr= np.ones((2,3))

In [22]:
arr+5             # every element gets added by 5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [23]:
arr*4           # every element gets multiplied by 4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [26]:
np.empty((3,4))       # it wuill generate a 2-D array with a very small number as the elements i.e. kind of empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.eye(5)             # a 5x5 identity matrix is generated. it is always a square matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# convert array to dataframe-

In [29]:
arr1= np.eye(5)

In [30]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
import pandas as pd

In [32]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [38]:
np.random.rand(2,3)         #it will generate a 2-D array of shape(2,3) i.e 2 rows and 3 columns filled with random data

array([[0.36546933, 0.54842056, 0.53079656],
       [0.48849511, 0.39472605, 0.72148357]])

In [34]:
np.random.randn(2,3)      # it wil also generate a 2-D array of shape(2,3) i.e 2 rows and 3 columns filled with random data

array([[ 0.61965207,  1.62926741, -1.63218184],
       [ 0.36823661,  0.95133631, -0.17106235]])

In [36]:
# difference between random.rand and random.randn is- The data generated by random.rand can have any mean and standard deviation. 
# But random.randn generates standard normalized data, i.e. the data has mean=0 and standard deviation=1. 
# Where ever we need normally distributed dataset we can use randn. 

In [39]:
np.random.randint(1,5, (3,4))       # it will generate a 2-D array of shape(3,4) filled with random integers between 1 and 5

array([[3, 2, 2, 2],
       [2, 3, 4, 4],
       [3, 4, 2, 3]])

In [40]:
arr2= np.random.randint(1,5, (3,4))  

In [41]:
arr2

array([[1, 2, 4, 4],
       [2, 4, 3, 4],
       [4, 3, 2, 1]])

In [42]:
arr2.size

12

In [43]:
arr2.shape

(3, 4)

In [44]:
# if we want to change shape of the array-
arr2.reshape(6,2)          # the shape given should be such that it satisfies the no. of elements in original array

array([[1, 2],
       [4, 4],
       [2, 4],
       [3, 4],
       [4, 3],
       [2, 1]])

In [45]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [46]:
arr2.reshape(4,3)

array([[1, 2, 4],
       [4, 2, 4],
       [3, 4, 4],
       [3, 2, 1]])

In [47]:
arr2.reshape(4,-1)       #we have not specified the other argument for shape, so there's a possibility that it will be considered as 3 so that the size i.e no. of elements= 12 will be satisfied as in the original array

array([[1, 2, 4],
       [4, 2, 4],
       [3, 4, 4],
       [3, 2, 1]])

In [49]:
# in place of -1 we can put any negative number and the output will be same.

In [50]:
# we can also reshape 2-D array to 3-D array-

arr2.reshape(2,2,3)     # it will generate 2 such (2,3) shape arrays thus resulting in 3-D array, such that the no. of elements= 2x2x3= 12 is the same as that in original array

array([[[1, 2, 4],
        [4, 2, 4]],

       [[3, 4, 4],
        [3, 2, 1]]])

In [51]:
# we can also reshape 2-D array to an n-dimensional array too-

arr2.reshape(2,2,3,1,1,1)

array([[[[[[1]]],


         [[[2]]],


         [[[4]]]],



        [[[[4]]],


         [[[2]]],


         [[[4]]]]],




       [[[[[3]]],


         [[[4]]],


         [[[4]]]],



        [[[[3]]],


         [[[2]]],


         [[[1]]]]]])

In [53]:
arr3= np.random.randint(1,10, (5,6))     #it will generate a 2-D array of shape(5,6) filled with random integers b/w 1 and 10

In [54]:
arr3

array([[8, 9, 9, 6, 3, 8],
       [5, 4, 4, 6, 5, 6],
       [2, 4, 8, 4, 9, 6],
       [3, 4, 2, 4, 7, 4],
       [5, 9, 2, 3, 2, 6]])

In [55]:
# filter out the data which are greater than 8- 

arr3>8

array([[False,  True,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False]])

In [57]:
arr3[arr3>8]      # it will give those elememts which are greater than 8

array([9, 9, 9, 9])

In [58]:
# extract data from a particular location of the 2-D array-
# extract 8,9 present in the 1st row of arr3-

arr3[0, [0,1]]

array([8, 9])

In [59]:
arr3[2:4, [1,2]]

array([[4, 8],
       [4, 2]])

In [60]:
arr4= np.random.randint(1,3, (3,3))     # it will generate a 2-D array of shape(3,3) with random integers between 1 and 3

In [61]:
arr5= np.random.randint(1,3, (3,3))     # it will generate a 2-D array of shape(3,3) with random integers between 1 and 3

In [62]:
arr4

array([[2, 1, 1],
       [1, 2, 2],
       [2, 2, 2]])

In [63]:
arr5

array([[1, 1, 2],
       [2, 2, 2],
       [2, 1, 2]])

In [64]:
# Addition of arrays-
arr4+arr5

array([[3, 2, 3],
       [3, 4, 4],
       [4, 3, 4]])

In [68]:
# Subtraction of arrays-
arr4-arr5

array([[ 1,  0, -1],
       [-1,  0,  0],
       [ 0,  1,  0]])

In [69]:
# Multiplication of arrays-
arr4*arr5     # it performs index wise i.e. element wise multiplication, not matrix multiplication

array([[2, 1, 2],
       [2, 4, 4],
       [4, 2, 4]])

In [67]:
# matrix multiplication-
arr4@arr5

array([[ 6,  5,  8],
       [ 9,  7, 10],
       [10,  8, 12]])

In [70]:
# Division of arrays-
arr4/arr5

array([[2. , 1. , 0.5],
       [0.5, 1. , 1. ],
       [1. , 2. , 1. ]])

In [71]:
arr4/0      

/tmp/ipykernel_77/3975123713.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [72]:
# in pandas such operation would have raised ZeroDivisonError but in numpy we get array with infinity elements

In [73]:
# Numpy- Broadcasting

In [74]:
arr6= np.zeros((3,4))

In [75]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
arr6+5        # this is called broadcasting, we are broadcasting 5 to arr6

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [77]:
a= np.array([1,2,3,4])

In [78]:
a

array([1, 2, 3, 4])

In [79]:
arr6+a          # the 1-D array a is added/broadcasted to arr6 column-wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [102]:
b= np.array([3,4,5])

In [103]:
b

array([3, 4, 5])

In [104]:
arr6+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [105]:
# we have to rotate the 1-D array b i.e take its Transpose and then broadcast/add it to arr6-
# but we can't rotate 1-D array so we make b a 2-D array-
b= np.array([[3,4,5]])
arr6+ b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [99]:
# so b gets added/broadcasted to arr6 row-wise

In [106]:
arr7= arr6+b.T

In [107]:
arr7

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [108]:
np.sqrt(arr7)        # it gives square root of each element

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [109]:
np.log10(arr7)         # it gives log base 10 of every element of array

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [110]:
np.exp(arr7)        # it gives exponential of every element

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [111]:
np.min(arr7)

3.0

In [112]:
np.max(arr7)

5.0

#### Numpy (Part-3)

In [1]:
import numpy as np

##### Numpy- Array manipulation- 

In [115]:
arr= np.random.randint(1,10, (4,4))

In [116]:
arr

array([[7, 8, 3, 9],
       [7, 8, 8, 9],
       [5, 6, 4, 3],
       [1, 2, 8, 7]])

In [117]:
arr.reshape(8,2)

array([[7, 8],
       [3, 9],
       [7, 8],
       [8, 9],
       [5, 6],
       [4, 3],
       [1, 2],
       [8, 7]])

In [118]:
arr.T      # taking transpose

array([[7, 7, 5, 1],
       [8, 8, 6, 2],
       [3, 8, 4, 8],
       [9, 9, 3, 7]])

In [119]:
arr.flatten()     # it will create 1-D array with all the elements of arr i.e flattening

array([7, 8, 3, 9, 7, 8, 8, 9, 5, 6, 4, 3, 1, 2, 8, 7])

In [120]:
np.expand_dims(arr, axis=1)    # it will expand 1 dimension. So, 2-D array becoms 3-D array, axis=1 means in the column direction

array([[[7, 8, 3, 9]],

       [[7, 8, 8, 9]],

       [[5, 6, 4, 3]],

       [[1, 2, 8, 7]]])

In [121]:
np.expand_dims(arr, axis=0)   # it will expand 1 dimension but in the row direction

array([[[7, 8, 3, 9],
        [7, 8, 8, 9],
        [5, 6, 4, 3],
        [1, 2, 8, 7]]])

In [124]:
data= np.array([[1], [2], [3]])    # we will get a 2-D array

In [123]:
data

array([[1],
       [2],
       [3]])

In [125]:
np.squeeze(data)     # it will squeeze the 2-D arary to a 1-D array

array([1, 2, 3])

In [126]:
np.repeat(data, 2)    # the elements of the array are repeated twice

array([1, 1, 2, 2, 3, 3])

In [127]:
np.roll(data, 2)       # it will roll the elements b y 2 steps

array([[2],
       [3],
       [1]])

In [129]:
# in the data array, element [1] was available at index=0, so roll by 2 means [1] will now be avaialble at index= 0+2= 2.
# element [2] was available at index=1, so roll by 2 means [2] will now be available at index= 1+2= 3= 0
# element [3] was available at index= 2, so roll by 2 means [3] will now be available at index= 2+2= 4= 1

In [130]:
np.diag(np.array([1,2,3,4]))    # these elements will be kept in the diagonal of a 2-D array with rest elements as 0

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

##### Numpy- Binary operators-

In [4]:
arr1= np.random.randint(1,10, (3,4))

In [3]:
arr2= np.random.randint(1,10, (3,4))

In [5]:
arr1

array([[8, 5, 8, 3],
       [7, 7, 8, 1],
       [3, 7, 1, 3]])

In [6]:
arr2

array([[6, 7, 1, 2],
       [5, 9, 5, 2],
       [9, 2, 8, 3]])

In [7]:
arr1+arr2

array([[14, 12,  9,  5],
       [12, 16, 13,  3],
       [12,  9,  9,  6]])

In [8]:
arr1*arr2           #index wise or element wise multiplication, not matrix multiplication

array([[48, 35,  8,  6],
       [35, 63, 40,  2],
       [27, 14,  8,  9]])

In [9]:
arr1/arr2

array([[1.33333333, 0.71428571, 8.        , 1.5       ],
       [1.4       , 0.77777778, 1.6       , 0.5       ],
       [0.33333333, 3.5       , 0.125     , 1.        ]])

In [10]:
arr1-arr2

array([[ 2, -2,  7,  1],
       [ 2, -2,  3, -1],
       [-6,  5, -7,  0]])

In [11]:
arr1**arr2      #index wise power operation, elements of arr1 raised to the power= elements of arr2

array([[  262144,    78125,        8,        9],
       [   16807, 40353607,    32768,        1],
       [   19683,       49,        1,       27]])

In [12]:
~arr1          # negation of arr1

array([[-9, -6, -9, -4],
       [-8, -8, -9, -2],
       [-4, -8, -2, -4]])

In [13]:
arr1>arr2            # comparision so it will give True or False

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [False,  True, False, False]])

##### Numpy- String functions-

In [19]:
arr3= np.array(["sudh kumar", "krish naik"])

In [20]:
arr3

array(['sudh kumar', 'krish naik'], dtype='<U10')

In [21]:
np.char.upper(arr3)          # inside char class all operations which we can do on strings is present, so here all the letters are made uppercase

array(['SUDH KUMAR', 'KRISH NAIK'], dtype='<U10')

In [22]:
np.char.capitalize(arr3)    # only the first letter is made capital

array(['Sudh kumar', 'Krish naik'], dtype='<U10')

In [23]:
np.char.title(arr3)      # first letter of each word in string is made capital

array(['Sudh Kumar', 'Krish Naik'], dtype='<U10')

##### Numpy- Mathematical operations-

In [24]:
arr1

array([[8, 5, 8, 3],
       [7, 7, 8, 1],
       [3, 7, 1, 3]])

In [25]:
np.sin(arr1)    # gives sine of every element

array([[ 0.98935825, -0.95892427,  0.98935825,  0.14112001],
       [ 0.6569866 ,  0.6569866 ,  0.98935825,  0.84147098],
       [ 0.14112001,  0.6569866 ,  0.84147098,  0.14112001]])

In [26]:
np.cos(arr1)    # gives cosine of every element

array([[-0.14550003,  0.28366219, -0.14550003, -0.9899925 ],
       [ 0.75390225,  0.75390225, -0.14550003,  0.54030231],
       [-0.9899925 ,  0.75390225,  0.54030231, -0.9899925 ]])

In [27]:
np.tan(arr1)        # gives tangent of every element

array([[-6.79971146, -3.38051501, -6.79971146, -0.14254654],
       [ 0.87144798,  0.87144798, -6.79971146,  1.55740772],
       [-0.14254654,  0.87144798,  1.55740772, -0.14254654]])

In [28]:
np.log10(arr1)        # gives log base 10 of every element

array([[0.90308999, 0.69897   , 0.90308999, 0.47712125],
       [0.84509804, 0.84509804, 0.90308999, 0.        ],
       [0.47712125, 0.84509804, 0.        , 0.47712125]])

In [29]:
np.exp(arr1)       # gives exponential of every element

array([[2.98095799e+03, 1.48413159e+02, 2.98095799e+03, 2.00855369e+01],
       [1.09663316e+03, 1.09663316e+03, 2.98095799e+03, 2.71828183e+00],
       [2.00855369e+01, 1.09663316e+03, 2.71828183e+00, 2.00855369e+01]])

In [30]:
np.power(arr1, 2)      # gives every element raised to the power 2

array([[64, 25, 64,  9],
       [49, 49, 64,  1],
       [ 9, 49,  1,  9]])

In [38]:
np.mean(arr1)         # gives mean value

5.083333333333333

In [32]:
np.median(arr1)      # gives median value of total array

6.0

In [34]:
np.std(arr1)       # gives standard deviation i.e. dispersion from mean

2.628635049264584

In [35]:
np.var(arr1)      # give variance

6.909722222222221

In [36]:
np.min(arr1)

1

In [37]:
np.max(arr1)

8

##### Numpy- Arithmetic operations

In [39]:
arr1

array([[8, 5, 8, 3],
       [7, 7, 8, 1],
       [3, 7, 1, 3]])

In [40]:
arr2

array([[6, 7, 1, 2],
       [5, 9, 5, 2],
       [9, 2, 8, 3]])

In [41]:
arr1-arr2

array([[ 2, -2,  7,  1],
       [ 2, -2,  3, -1],
       [-6,  5, -7,  0]])

In [42]:
# this we can perform using the function subtract-
np.subtract(arr1, arr2)

array([[ 2, -2,  7,  1],
       [ 2, -2,  3, -1],
       [-6,  5, -7,  0]])

In [43]:
np.multiply(arr1, arr2)

array([[48, 35,  8,  6],
       [35, 63, 40,  2],
       [27, 14,  8,  9]])

In [44]:
np.mod(arr1,arr2)      # mod gives the remainder after elements of arr1 are divided by arr2

array([[2, 5, 0, 1],
       [2, 7, 3, 1],
       [3, 1, 1, 0]])

In [45]:
np.power(arr1, arr2)

array([[  262144,    78125,        8,        9],
       [   16807, 40353607,    32768,        1],
       [   19683,       49,        1,       27]])

In [46]:
np.sqrt(arr1)

array([[2.82842712, 2.23606798, 2.82842712, 1.73205081],
       [2.64575131, 2.64575131, 2.82842712, 1.        ],
       [1.73205081, 2.64575131, 1.        , 1.73205081]])

##### Numpy- Statistical functions

In [47]:
arr2

array([[6, 7, 1, 2],
       [5, 9, 5, 2],
       [9, 2, 8, 3]])

In [48]:
np.mean(arr2)

4.916666666666667

In [49]:
np.median(arr2)

5.0

In [50]:
np.std(arr2)

2.7826346428439996

In [51]:
np.var(arr2)

7.7430555555555545

In [52]:
np.min(arr2)

1

In [54]:
np.max(arr2)

9

#### Numpy (Part-4)

##### sort, search, counting functions-

In [55]:
import numpy as np

In [56]:
arr= np.array([4,2,8,5,3,9,12,56])

In [57]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [58]:
np.sort(arr)         # it sorts the array in ascending order

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [59]:
np.searchsorted(arr, 6)

5

In [60]:
# searchsorted() function finds the position where the given element has to be entered to maintain order i.e. sorted

In [61]:
arr1= np.array([0,324,645,65,6,6,0,0,0,234])

In [62]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [63]:
np.count_nonzero(arr1)        # returns how many non-zero elements are present in the array

6

In [64]:
np.where(arr1>0)      # it will give the indices of elements where this condition is satisfied

(array([1, 2, 3, 4, 5, 9]),)

In [65]:
np.extract(arr1>2, arr1)     # it will extract all those elements which satisfy this condition

array([324, 645,  65,   6,   6, 234])

##### Numpy- Byte swapping-

In [66]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [67]:
arr.byteswap()         # it gives the byte version of the elements of the array

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [68]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [70]:
# so byteswap() is temporary during run time, to make it permanent we can do inplace= True

In [71]:
arr.byteswap(inplace= True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [72]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [73]:
# So, permanently the elements of the array are swapped with their byte version

##### Numpy- copies and views-

In [74]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [75]:
a= np.copy(arr1)        # deep copy

In [76]:
b= arr1.view()

In [77]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [78]:
b[0]= 234

In [79]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [80]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [81]:
# so, view() function is a shallow copy

##### Numpy- Matrix library-

In [82]:
import numpy.matlib as nm

In [83]:
nm.zeros(5)           # it will generate a matrix with 5 zeroes

matrix([[0., 0., 0., 0., 0.]])

In [84]:
nm.ones(5)          # it will generate a matrix with 5 ones

matrix([[1., 1., 1., 1., 1.]])

In [86]:
# matrix is a subclass of array

In [87]:
nm.eye(4)           # a 4x4 identity matrix is generated

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

##### Numpy- Linear algebra-

In [88]:
arr2= np.random.randint([[2,3], [4,5]])

In [93]:
arr3= np.random.randint([[5,3], [2,5]])

In [90]:
arr2

array([[1, 1],
       [0, 0]])

In [94]:
arr3

array([[3, 0],
       [1, 3]])

In [95]:
np.dot(arr2, arr3)

array([[4, 3],
       [0, 0]])

In [96]:
arr2@arr3

array([[4, 3],
       [0, 0]])

In [97]:
# so dot product is simply matrix multiplication